### ISSUE TITLE
Unable to authenticate via OAuth2

### ISSUE THREAD

**Issue by mdipirro** [okta/okta-sdk-java#786]
### Describe the bug?

Hello, we're trying to upgrade the Java SDK from version 8.2.1 to 10.0.0. When using 8.2.1, we had set up an OAuth service application on Okta and would authenticate using a public/private key pair, as described in the old README: https://github.com/okta/okta-sdk-java/tree/okta-sdk-root-8.2.1#oauth-20

When we upgraded to 10.0.0, however, the authentication broke. When the application attempts to authenticate to Okta we're now getting the following exception:

```
Exception in thread "main" com.okta.sdk.impl.oauth2.OAuth2TokenRetrieverException: Exception while trying to get OAuth2 access token for client id ...
at com.okta.sdk.impl.oauth2.AccessTokenRetrieverServiceImpl.getOAuth2AccessToken(AccessTokenRetrieverServiceImpl.java:129)
at com.okta.sdk.impl.oauth2.OAuth2ClientCredentials.eagerFetchOAuth2AccessToken(OAuth2ClientCredentials.java:44)
at com.okta.sdk.impl.oauth2.OAuth2ClientCredentials.<init>(OAuth2ClientCredentials.java:37)
at com.okta.sdk.impl.client.DefaultClientBuilder.build(DefaultClientBuilder.java:370)
...
Caused by: org.springframework.web.client.RestClientException: Authentication undefined: OAuth_2.0
at org.openapitools.client.ApiClient.updateParamsForAuth(ApiClient.java:842)
at org.openapitools.client.ApiClient.invokeAPI(ApiClient.java:630)
at com.okta.sdk.impl.oauth2.AccessTokenRetrieverServiceImpl.getOAuth2AccessToken(AccessTokenRetrieverServiceImpl.java:105)
```

We also found a question in the Okta developer forum about this issue: https://devforum.okta.com/t/okta-java-management-sdk-oauth-service-app/22455

### What is expected to happen?

The SDK client builder should allow authentication via OAuth 2.

### What is the actual behavior?

An exception is thrown:

```
Exception in thread "main" com.okta.sdk.impl.oauth2.OAuth2TokenRetrieverException: Exception while trying to get OAuth2 access token for client id ...
at com.okta.sdk.impl.oauth2.AccessTokenRetrieverServiceImpl.getOAuth2AccessToken(AccessTokenRetrieverServiceImpl.java:129)
at com.okta.sdk.impl.oauth2.OAuth2ClientCredentials.eagerFetchOAuth2AccessToken(OAuth2ClientCredentials.java:44)
at com.okta.sdk.impl.oauth2.OAuth2ClientCredentials.<init>(OAuth2ClientCredentials.java:37)
at com.okta.sdk.impl.client.DefaultClientBuilder.build(DefaultClientBuilder.java:370)
...
Caused by: org.springframework.web.client.RestClientException: Authentication undefined: OAuth_2.0
at org.openapitools.client.ApiClient.updateParamsForAuth(ApiClient.java:842)
at org.openapitools.client.ApiClient.invokeAPI(ApiClient.java:630)
at com.okta.sdk.impl.oauth2.AccessTokenRetrieverServiceImpl.getOAuth2AccessToken(AccessTokenRetrieverServiceImpl.java:105)
```

### Reproduction Steps?

Build an Okta client using the guidelines for SDK 8.2.1: https://github.com/okta/okta-sdk-java/tree/okta-sdk-root-8.2.1#oauth-20

### Java Version

openjdk 11.0.9.1 2020-11-04
OpenJDK Runtime Environment 18.9 (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.9.1+1, mixed mode)

### SDK Version

10.0.0

**Comment by petermorlion** [comment]
Same problem here. If I look at the [Okta OpenAPI specs](https://github.com/okta/okta-management-openapi-spec/blob/master/dist/spec.yaml), I see there is only one securityDefinition: api_token. Could this be the problem? I checked the code and think the SDK switched from a custom implementation (although I didn't dig too deep) to a client generated form the OpenAPI spec.
That would mean that v10 of the Okta SDK supports only a single auth mechanism?

**Comment by clementdenis** [comment]
I fixed the problem in [this branch on my fork](https://github.com/okta/okta-sdk-java/compare/master...clementdenis:okta-sdk-java:private_key_auth?expand=1).

There were other issues besides the stacktrace in this ticket:
- The name of the auth scheme was incorrect indeed (`OAuth_2.0` instead of `oauth`)
- The base path was not set when using a private key for auth
- The request to obtain the token was using query params instead of form params
- The json binding of OAuth2AccessToken was wrong => I used `@JsonNaming(SnakeCaseStrategy.class)` to fix it quickly, might be worth setting the json field names explicitly with `@JsonProperty`
- The access token was not properly set on the client => there is currently no auto-refresh of the token, so the client is valid for at most 1 hour, there's probably a way to fix this

**Comment by arvindkrishnakumar-okta** [comment]
https://github.com/okta/okta-sdk-java/pull/793 should fix this. Will merge this PR and cut a release soon.

**Comment by arvindkrishnakumar-okta** [comment]
Fixed in 10.1.0
