### ISSUE TITLE
okta-authn-sdk-api:2.0.9 does not work with okta-sdk-impl:10.0.0

### ISSUE THREAD

**Issue by sunilchaurha** [okta/okta-sdk-java#799]
### Describe the bug?

I am trying to implement Okta core API and Okta login wrapper for my organization, which should do all user operation and user login authentication too.
I am using okta-authn-sdk-api:2.0.9 version  with okta-sdk-impl:10.0.0 to support above said requirement.
But I am getting below error. 

Analysis: When I looked into dependencies in okta-authn-sdk-api:2.0.9 it's referring to okta-sdk-impl:8.2.2 via okta-parent:2.0.9.
I don't get a choice to change the dependency for okta-sdk-impl to the one which I need.

Error:
java.lang.NoClassDefFoundError: com/okta/sdk/impl/client/BaseClient
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at com.okta.authn.sdk.impl.client.DefaultAuthenticationClientBuilder.build(DefaultAuthenticationClientBuilder.java:212)
	at com.mycompany.okta.client.OktaClientFactory.<init>(OktaClientFactory.java:42)
	at com.mycompany.okta.client.OktaClientFactory.getInstance(OktaClientFactory.java:48)
	at com.mycompany.okta.service.login.OktaUserAuthnServiceImpl.<init>(OktaUserAuthnServiceImpl.java:11)
	at com.mycompany.okta.service.test.OktaUserAuthenticationServiceTest.testGetUserById(OktaUserAuthenticationServiceTest.java:29)

### What is expected to happen?

I should be able to use okta-sdk-impl:10.0.0 version with okta-authn-sdk-api, as 10.0.0 is the latest release.
I should not get classnot found exception.

### What is the actual behavior?

Getting java.lang.NoClassDefFoundError: com/okta/sdk/impl/client/BaseClient

### Reproduction Steps?

Getting java.lang.NoClassDefFoundError: com/okta/sdk/impl/client/BaseClient

### Additional Information?

Dependencies:
		<okta.sdk.version>10.0.0</okta.sdk.version>
		<okta.authn.version>2.0.9</okta.authn.version>

 <dependency>
		    <groupId>com.okta.authn.sdk</groupId>
		    <artifactId>okta-authn-sdk-api</artifactId>
		    <version>${okta.authn.version}</version>
		</dependency>
		<dependency>
		    <groupId>com.okta.authn.sdk</groupId>
		    <artifactId>okta-authn-sdk-impl</artifactId>
		    <version>${okta.authn.version}</version>
		</dependency>
	    
		<dependency>
			<groupId>com.okta.sdk</groupId>
			<artifactId>okta-sdk-api</artifactId>
			<version>${okta.sdk.version}</version>
		</dependency>
		<dependency>
			<groupId>com.okta.sdk</groupId>
			<artifactId>okta-sdk-impl</artifactId>
			<version>${okta.sdk.version}</version>
		</dependency>

### Java Version

openjdk version "11.0.7" 2020-04-14 LTS
OpenJDK Runtime Environment Corretto-11.0.7.10.1 (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.7.10.1 (build 11.0.7+10-LTS, mixed mode)

### SDK Version

11.

### OS version

Windows 10

**Comment by arvindkrishnakumar-okta** [comment]
Thanks for posting!We don't officially support okta-auth-java to work with 10.x versions of Okta Java Mgmt SDK yet.We have plans to add support, stay tuned for further updates.On Jan 17, 2023, at 2:36 AM, Sunil Chauraha ***@***.***> wrote:﻿

This message originated outside your organization.
  

Describe the bug?
I am trying to implement Okta core API and Okta login wrapper for my organization, which should do all user operation and user login authentication too.
I am using okta-authn-sdk-api:2.0.9 version  with okta-sdk-impl:10.0.0 to support above said requirement.
But I am getting below error.
Analysis: When I looked into dependencies in okta-authn-sdk-api:2.0.9 it's referring to okta-sdk-impl:8.2.2 via okta-parent:2.0.9.
I don't get a choice to change the dependency for okta-sdk-impl to the one which I need.
Error:
java.lang.NoClassDefFoundError: com/okta/sdk/impl/client/BaseClient
at java.base/java.lang.ClassLoader.defineClass1(Native Method)
at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
at com.okta.authn.sdk.impl.client.DefaultAuthenticationClientBuilder.build(DefaultAuthenticationClientBuilder.java:212)
at com.mycompany.okta.client.OktaClientFactory.(OktaClientFactory.java:42)
at com.mycompany.okta.client.OktaClientFactory.getInstance(OktaClientFactory.java:48)
at com.mycompany.okta.service.login.OktaUserAuthnServiceImpl.(OktaUserAuthnServiceImpl.java:11)
at com.mycompany.okta.service.test.OktaUserAuthenticationServiceTest.testGetUserById(OktaUserAuthenticationServiceTest.java:29)
What is expected to happen?
I should be able to use okta-sdk-impl:10.0.0 version with okta-authn-sdk-api, as 10.0.0 is the latest release.
I should not get classnot found exception.
What is the actual behavior?
Getting java.lang.NoClassDefFoundError: com/okta/sdk/impl/client/BaseClient
Reproduction Steps?
Getting java.lang.NoClassDefFoundError: com/okta/sdk/impl/client/BaseClient
Additional Information?
Dependencies:
<okta.sdk.version>10.0.0</okta.sdk.version>
<okta.authn.version>2.0.9</okta.authn.version>
 
		    com.okta.authn.sdk
		    okta-authn-sdk-api
		    ${okta.authn.version}
		
		
		    com.okta.authn.sdk
		    okta-authn-sdk-impl
		    ${okta.authn.version}
		
	<dependency>
		<groupId>com.okta.sdk</groupId>
		<artifactId>okta-sdk-api</artifactId>
		<version>${okta.sdk.version}</version>
	</dependency>
	<dependency>
		<groupId>com.okta.sdk</groupId>
		<artifactId>okta-sdk-impl</artifactId>
		<version>${okta.sdk.version}</version>
	</dependency>

Java Version
openjdk version "11.0.7" 2020-04-14 LTS
OpenJDK Runtime Environment Corretto-11.0.7.10.1 (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.7.10.1 (build 11.0.7+10-LTS, mixed mode)
SDK Version



OS version
Windows 10

**Comment by arvindkrishnakumar-okta** [comment]
This issue duplicates https://github.com/okta/okta-auth-java/issues/255On Jan 17, 2023, at 10:09 AM, Arvind Krishnakumar ***@***.***> wrote:﻿

This message originated outside your organization.
  

Thanks for posting!We don't officially support okta-auth-java to work with 10.x versions of Okta Java Mgmt SDK yet.We have plans to add support, stay tuned for further updates.On Jan 17, 2023, at 2:36 AM, Sunil Chauraha ***@***.***> wrote:﻿

This message originated outside your organization.
  

Describe the bug?
I am trying to implement Okta core API and Okta login wrapper for my organization, which should do all user operation and user login authentication too.
I am using okta-authn-sdk-api:2.0.9 version  with okta-sdk-impl:10.0.0 to support above said requirement.
But I am getting below error.
Analysis: When I looked into dependencies in okta-authn-sdk-api:2.0.9 it's referring to okta-sdk-impl:8.2.2 via okta-parent:2.0.9.
I don't get a choice to change the dependency for okta-sdk-impl to the one which I need.
Error:
java.lang.NoClassDefFoundError: com/okta/sdk/impl/client/BaseClient
at java.base/java.lang.ClassLoader.defineClass1(Native Method)
at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
at com.okta.authn.sdk.impl.client.DefaultAuthenticationClientBuilder.build(DefaultAuthenticationClientBuilder.java:212)
at com.mycompany.okta.client.OktaClientFactory.(OktaClientFactory.java:42)
at com.mycompany.okta.client.OktaClientFactory.getInstance(OktaClientFactory.java:48)
at com.mycompany.okta.service.login.OktaUserAuthnServiceImpl.(OktaUserAuthnServiceImpl.java:11)
at com.mycompany.okta.service.test.OktaUserAuthenticationServiceTest.testGetUserById(OktaUserAuthenticationServiceTest.java:29)
What is expected to happen?
I should be able to use okta-sdk-impl:10.0.0 version with okta-authn-sdk-api, as 10.0.0 is the latest release.
I should not get classnot found exception.
What is the actual behavior?
Getting java.lang.NoClassDefFoundError: com/okta/sdk/impl/client/BaseClient
Reproduction Steps?
Getting java.lang.NoClassDefFoundError: com/okta/sdk/impl/client/BaseClient
Additional Information?
Dependencies:
<okta.sdk.version>10.0.0</okta.sdk.version>
<okta.authn.version>2.0.9</okta.authn.version>
 
		    com.okta.authn.sdk
		    okta-authn-sdk-api
		    ${okta.authn.version}
		
		
		    com.okta.authn.sdk
		    okta-authn-sdk-impl
		    ${okta.authn.version}
		
	<dependency>
		<groupId>com.okta.sdk</groupId>
		<artifactId>okta-sdk-api</artifactId>
		<version>${okta.sdk.version}</version>
	</dependency>
	<dependency>
		<groupId>com.okta.sdk</groupId>
		<artifactId>okta-sdk-impl</artifactId>
		<version>${okta.sdk.version}</version>
	</dependency>

Java Version
openjdk version "11.0.7" 2020-04-14 LTS
OpenJDK Runtime Environment Corretto-11.0.7.10.1 (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.7.10.1 (build 11.0.7+10-LTS, mixed mode)
SDK Version



OS version
Windows 10
